### ISSUE TITLE
Add environment setup to readme.

### ISSUE THREAD

**Issue by mattmonihan** [mattmonihan/solid-object#1]
I think I got this setup far enough to check out what you've done so far but I was getting some errors looking for assets and such.

To get things started, I ran:
```bash
$ bundle install
$ rake db:migrate
$ bundle exec rails server
```

Am I missing anything else?

**Comment by mattmonihan** [comment]
I was having trouble with the bower.json file.

It looks like 
```JSON
{
  "lib": {
    "name": "bower-rails generated lib assets",
    "dependencies": {
      "threex"      : "git@github.com:rharriso/threex.git",
      "gsvpano.js"  : "https://github.com/rharriso/GSVPano.js/blob/master/src/GSVPano.js"
    }
  },
  "vendor": {
    "name": "bower-rails generated vendor assets",
    "dependencies": {
      "three.js"    : "https://raw.github.com/mrdoob/three.js/master/build/three.js"
    }
  }
}
```

and when running ```$ bower install```
I get:
```BASH
Matthews-MacBook-Air:solid-object mattmonihan$ bower install
bower EINVALID      Failed to read /Users/mattmonihan/Sites/solid-object/bower.json

Additional error details:
No name property set
```


I think there may be something different about your environment. If I get rid of bower.json, and run ```$ bower install formbuilder --save``` it looks like it installs the right components.

**Comment by javonharper** [comment]
Try running `rake bower:install`. The bower-rails gem looks at the 'Bowerfile' to determine it's config & dependencies. It also looks like the  bower.json file isn't necessary if you use the Bowerfile. I've removed the file and updated the README.

**Comment by mattmonihan** [comment]
Ok, I think I'm good. The components got installed. I added /bower_components and /node_modules to gitignore.
